development:
  adapter: postgresql
  database: spec_relation_reuse_dev
  username: postgres
  host: localhost
  min_messages: WARNING

test:
  adapter: postgresql
  database: spec_relation_reuse_test
  username: postgres
  host: localhost
